name: Auto Post

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

      - name: Post to Facebook
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node ./src/index.js